// <auto-generated />
using System;
using MetricService.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetricService.DAL.Migrations
{
    [DbContext(typeof(MetricServiceDbContext))]
    partial class MetricServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetricService.Domain.Models.HealthMetricsBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("BloodPressureDia")
                        .HasColumnType("smallint")
                        .HasComment("Нижнее артериальное давление (мм рт. ст.)");

                    b.Property<short?>("BloodPressureSys")
                        .HasColumnType("smallint")
                        .HasComment("Верхнее артериальное давление (мм рт. ст.)");

                    b.Property<float?>("BodyFatPercentage")
                        .HasColumnType("real")
                        .HasComment("Процент жира в организме");

                    b.Property<short>("HeartRate")
                        .HasColumnType("smallint")
                        .HasComment("Частота сердечных сокращений (ударов/мин)");

                    b.Property<DateTime>("MetricDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата замера показателя");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор пользователя");

                    b.Property<short?>("WaterIntake")
                        .HasColumnType("smallint")
                        .HasComment("Потребление воды (мл)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HealthMetricsBase", t =>
                        {
                            t.HasComment("Базовые медицинские показатели");
                        });
                });

            modelBuilder.Entity("MetricService.Domain.Models.PhysicalActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("EnergyEquivalent")
                        .HasColumnType("real")
                        .HasComment("Метаболический эквивалент");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Наименование физической активности");

                    b.HasKey("Id");

                    b.ToTable("PhysicalActivities", t =>
                        {
                            t.HasComment("Тренировки");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnergyEquivalent = 5f,
                            Name = "Аквааэробика (умеренный темп)"
                        },
                        new
                        {
                            Id = 2,
                            EnergyEquivalent = 5f,
                            Name = "Акваслайдинг (водные горки)"
                        },
                        new
                        {
                            Id = 3,
                            EnergyEquivalent = 4f,
                            Name = "Активные домашние животные (игра с собакой)"
                        },
                        new
                        {
                            Id = 4,
                            EnergyEquivalent = 8f,
                            Name = "Альпинизм (взбирание в горы)"
                        },
                        new
                        {
                            Id = 5,
                            EnergyEquivalent = 4.5f,
                            Name = "Бадминтон"
                        },
                        new
                        {
                            Id = 6,
                            EnergyEquivalent = 7f,
                            Name = "Бег трусцой (8 км/ч)"
                        },
                        new
                        {
                            Id = 7,
                            EnergyEquivalent = 10f,
                            Name = "Бокс"
                        },
                        new
                        {
                            Id = 8,
                            EnergyEquivalent = 8f,
                            Name = "Борьба дзюдо (групповые занятия)"
                        },
                        new
                        {
                            Id = 9,
                            EnergyEquivalent = 5f,
                            Name = "Быстрая ходьба (более 6 км/ч)"
                        },
                        new
                        {
                            Id = 10,
                            EnergyEquivalent = 8f,
                            Name = "Быстрое восхождение по лестнице"
                        },
                        new
                        {
                            Id = 11,
                            EnergyEquivalent = 6f,
                            Name = "Велоспорт (10–16 км/ч)"
                        },
                        new
                        {
                            Id = 12,
                            EnergyEquivalent = 5.5f,
                            Name = "Верховая езда"
                        },
                        new
                        {
                            Id = 13,
                            EnergyEquivalent = 5f,
                            Name = "Водная аэробика"
                        },
                        new
                        {
                            Id = 14,
                            EnergyEquivalent = 4f,
                            Name = "Волейбол"
                        },
                        new
                        {
                            Id = 15,
                            EnergyEquivalent = 12f,
                            Name = "Высокогорные восхождения"
                        },
                        new
                        {
                            Id = 16,
                            EnergyEquivalent = 15f,
                            Name = "Высокоинтенсивные интервальные тренировки (HIIT)"
                        },
                        new
                        {
                            Id = 17,
                            EnergyEquivalent = 6f,
                            Name = "Гимнастика с утяжелителями"
                        },
                        new
                        {
                            Id = 18,
                            EnergyEquivalent = 12f,
                            Name = "Гонка на выносливость (железный человек)"
                        },
                        new
                        {
                            Id = 19,
                            EnergyEquivalent = 8f,
                            Name = "Горнолыжный спорт"
                        },
                        new
                        {
                            Id = 20,
                            EnergyEquivalent = 8f,
                            Name = "Гребля на байдарках или каноэ"
                        },
                        new
                        {
                            Id = 21,
                            EnergyEquivalent = 3.5f,
                            Name = "Домашние дела (уборка дома)"
                        },
                        new
                        {
                            Id = 22,
                            EnergyEquivalent = 2f,
                            Name = "Дыхательная гимнастика"
                        },
                        new
                        {
                            Id = 23,
                            EnergyEquivalent = 3f,
                            Name = "Езда на велосипеде (менее 10 км/ч)"
                        },
                        new
                        {
                            Id = 24,
                            EnergyEquivalent = 10f,
                            Name = "Забеги на длинные дистанции (марафон)"
                        },
                        new
                        {
                            Id = 25,
                            EnergyEquivalent = 4f,
                            Name = "Заниматься танцами (танго, вальс)"
                        },
                        new
                        {
                            Id = 26,
                            EnergyEquivalent = 2.5f,
                            Name = "Занятие йогой (медленные позы)"
                        },
                        new
                        {
                            Id = 27,
                            EnergyEquivalent = 8f,
                            Name = "Зимние виды спорта (лыжи, сноуборд)"
                        },
                        new
                        {
                            Id = 28,
                            EnergyEquivalent = 5f,
                            Name = "Игра в теннис (парный режим)"
                        },
                        new
                        {
                            Id = 29,
                            EnergyEquivalent = 8f,
                            Name = "Игры в баскетбол (не соревновательные)"
                        },
                        new
                        {
                            Id = 30,
                            EnergyEquivalent = 4.5f,
                            Name = "Йога (силовая практика)"
                        },
                        new
                        {
                            Id = 31,
                            EnergyEquivalent = 12f,
                            Name = "Кардиотренажёры (интервал-тренировка)"
                        },
                        new
                        {
                            Id = 32,
                            EnergyEquivalent = 10f,
                            Name = "Классическое плавание (энергичное)"
                        },
                        new
                        {
                            Id = 33,
                            EnergyEquivalent = 8f,
                            Name = "Командные игры (регби, хоккей)"
                        },
                        new
                        {
                            Id = 34,
                            EnergyEquivalent = 2.5f,
                            Name = "Концерт (стояние, хоровое исполнение песен)"
                        },
                        new
                        {
                            Id = 35,
                            EnergyEquivalent = 7f,
                            Name = "Конькобежный спорт"
                        },
                        new
                        {
                            Id = 36,
                            EnergyEquivalent = 10f,
                            Name = "Кроссфит"
                        },
                        new
                        {
                            Id = 37,
                            EnergyEquivalent = 3f,
                            Name = "Купание в море (игры, плескание)"
                        },
                        new
                        {
                            Id = 38,
                            EnergyEquivalent = 7f,
                            Name = "Легкая атлетика (пробежки)"
                        },
                        new
                        {
                            Id = 39,
                            EnergyEquivalent = 1f,
                            Name = "Лежачий покой"
                        },
                        new
                        {
                            Id = 40,
                            EnergyEquivalent = 5.5f,
                            Name = "Летний туризм (велосипедные прогулки)"
                        },
                        new
                        {
                            Id = 41,
                            EnergyEquivalent = 10f,
                            Name = "Марафон"
                        },
                        new
                        {
                            Id = 42,
                            EnergyEquivalent = 7f,
                            Name = "Обычная игра в футбол (любительский уровень)"
                        },
                        new
                        {
                            Id = 43,
                            EnergyEquivalent = 6f,
                            Name = "Перемещение тяжелой техники"
                        },
                        new
                        {
                            Id = 44,
                            EnergyEquivalent = 6f,
                            Name = "Перенос тяжелых предметов (сумки, коробки)"
                        },
                        new
                        {
                            Id = 45,
                            EnergyEquivalent = 3.5f,
                            Name = "Пилатес"
                        },
                        new
                        {
                            Id = 46,
                            EnergyEquivalent = 6f,
                            Name = "Плавание (легкий темп)"
                        },
                        new
                        {
                            Id = 47,
                            EnergyEquivalent = 5f,
                            Name = "Погрузка мебели"
                        },
                        new
                        {
                            Id = 48,
                            EnergyEquivalent = 3f,
                            Name = "Поездка на мотоцикле"
                        },
                        new
                        {
                            Id = 49,
                            EnergyEquivalent = 4f,
                            Name = "Покраска стен (ручной труд)"
                        },
                        new
                        {
                            Id = 50,
                            EnergyEquivalent = 3.5f,
                            Name = "Прогулочный шаг (4–5 км/ч)"
                        },
                        new
                        {
                            Id = 51,
                            EnergyEquivalent = 1.3f,
                            Name = "Просмотр телевизора"
                        },
                        new
                        {
                            Id = 52,
                            EnergyEquivalent = 10f,
                            Name = "Профессиональный бег (12 км/ч)"
                        },
                        new
                        {
                            Id = 53,
                            EnergyEquivalent = 1.5f,
                            Name = "Работа в офисе (сидячая)"
                        },
                        new
                        {
                            Id = 54,
                            EnergyEquivalent = 4f,
                            Name = "Работа с садовыми инструментами (газонокосилка)"
                        },
                        new
                        {
                            Id = 55,
                            EnergyEquivalent = 2.3f,
                            Name = "Растяжка"
                        },
                        new
                        {
                            Id = 56,
                            EnergyEquivalent = 5f,
                            Name = "Ремонт квартиры (перестановка мебели)"
                        },
                        new
                        {
                            Id = 57,
                            EnergyEquivalent = 3f,
                            Name = "Рыбалка (ловля рыбы удочкой)"
                        },
                        new
                        {
                            Id = 58,
                            EnergyEquivalent = 4f,
                            Name = "Садоводство (посадка растений, прополка)"
                        },
                        new
                        {
                            Id = 59,
                            EnergyEquivalent = 8f,
                            Name = "Санный спорт (гонки на санях)"
                        },
                        new
                        {
                            Id = 60,
                            EnergyEquivalent = 6f,
                            Name = "Сельскохозяйственная работа (ручная обработка земли)"
                        },
                        new
                        {
                            Id = 61,
                            EnergyEquivalent = 8f,
                            Name = "Серфинг (катание на волнах)"
                        },
                        new
                        {
                            Id = 62,
                            EnergyEquivalent = 3.5f,
                            Name = "Силовые тренировки (вес менее 5 кг)"
                        },
                        new
                        {
                            Id = 63,
                            EnergyEquivalent = 8f,
                            Name = "Скалолазание (скалодром)"
                        },
                        new
                        {
                            Id = 64,
                            EnergyEquivalent = 4.3f,
                            Name = "Скандинавская ходьба"
                        },
                        new
                        {
                            Id = 65,
                            EnergyEquivalent = 4.5f,
                            Name = "Совместная семейная прогулка (быстрая ходьба)"
                        },
                        new
                        {
                            Id = 66,
                            EnergyEquivalent = 0.9f,
                            Name = "Сон"
                        },
                        new
                        {
                            Id = 67,
                            EnergyEquivalent = 13f,
                            Name = "Соревнования по бегу на короткие дистанции"
                        },
                        new
                        {
                            Id = 68,
                            EnergyEquivalent = 4f,
                            Name = "Спокойная велосипедная поездка (10–16 км/ч)"
                        },
                        new
                        {
                            Id = 69,
                            EnergyEquivalent = 8f,
                            Name = "Спортивная гимнастика"
                        },
                        new
                        {
                            Id = 70,
                            EnergyEquivalent = 15f,
                            Name = "Спринт"
                        },
                        new
                        {
                            Id = 71,
                            EnergyEquivalent = 3.5f,
                            Name = "Стрельба из лука"
                        },
                        new
                        {
                            Id = 72,
                            EnergyEquivalent = 2.3f,
                            Name = "Стретчинг (растяжка мышц)"
                        },
                        new
                        {
                            Id = 73,
                            EnergyEquivalent = 4.5f,
                            Name = "Строительство забора"
                        },
                        new
                        {
                            Id = 74,
                            EnergyEquivalent = 2.5f,
                            Name = "Тай-чи (умеренный темп)"
                        },
                        new
                        {
                            Id = 75,
                            EnergyEquivalent = 6f,
                            Name = "Танцы (быстрое движение, зумба)"
                        },
                        new
                        {
                            Id = 76,
                            EnergyEquivalent = 4f,
                            Name = "Танцы (социальные танцы)"
                        },
                        new
                        {
                            Id = 77,
                            EnergyEquivalent = 6f,
                            Name = "Туризм пеший (горные походы)"
                        },
                        new
                        {
                            Id = 78,
                            EnergyEquivalent = 5.5f,
                            Name = "Упражнения на велотренажере (умеренная нагрузка)"
                        },
                        new
                        {
                            Id = 79,
                            EnergyEquivalent = 4f,
                            Name = "Ходьба (5–6 км/ч)"
                        },
                        new
                        {
                            Id = 80,
                            EnergyEquivalent = 5f,
                            Name = "Хождение пешком (6–7 км/ч)"
                        },
                        new
                        {
                            Id = 81,
                            EnergyEquivalent = 8f,
                            Name = "Хождение пешком вверх по лестнице"
                        },
                        new
                        {
                            Id = 82,
                            EnergyEquivalent = 7f,
                            Name = "Чистка снега лопатой"
                        },
                        new
                        {
                            Id = 83,
                            EnergyEquivalent = 7f,
                            Name = "Эллипсоид (умеренный темп)"
                        });
                });

            modelBuilder.Entity("MetricService.Domain.Models.Sleep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasComment("примечания о качестве сна");

                    b.Property<DateTime>("EndSleep")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("время окончания сна");

                    b.Property<short>("QualityRating")
                        .HasColumnType("smallint")
                        .HasComment("качество сна по 5-ой системе");

                    b.Property<DateTime>("StartSleep")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("время начала сна");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasComment("идентификатор пользователя");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sleeps", t =>
                        {
                            t.HasComment("Сон");
                        });
                });

            modelBuilder.Entity("MetricService.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasComment("дата рождения");

                    b.Property<short>("Height")
                        .HasColumnType("smallint")
                        .HasComment("рост в сантиметрах");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasComment("Вес в килограммах");

                    b.HasKey("Id");

                    b.ToTable("Users", t =>
                        {
                            t.HasComment("Пользователь");
                        });
                });

            modelBuilder.Entity("MetricService.Domain.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Описание");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время окончания тренировки");

                    b.Property<int>("PhysicalActivityId")
                        .HasColumnType("integer")
                        .HasComment("Физ. активность");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время начала тренировки");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id");

                    b.HasIndex("PhysicalActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts", t =>
                        {
                            t.HasComment("Тренировки");
                        });
                });

            modelBuilder.Entity("MetricService.Domain.Models.HealthMetricsBase", b =>
                {
                    b.HasOne("MetricService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetricService.Domain.Models.Sleep", b =>
                {
                    b.HasOne("MetricService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetricService.Domain.Models.Workout", b =>
                {
                    b.HasOne("MetricService.Domain.Models.PhysicalActivity", "PhysicalActivity")
                        .WithMany()
                        .HasForeignKey("PhysicalActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MetricService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysicalActivity");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
