// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolyclinicService.DAL.Contexts;

#nullable disable

namespace PolyclinicService.DAL.Migrations
{
    [DbContext(typeof(PolyclinicServiceDbContext))]
    partial class PolyclinicServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolyclinicDoctors", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PolyclinicId")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId", "PolyclinicId");

                    b.HasIndex("PolyclinicId");

                    b.ToTable("PolyclinicDoctors");
                });

            modelBuilder.Entity("PolyclinicService.Domain.Models.Entities.AppointmentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор результата приёма");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentSlotId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор слота на приём к врачу из графика");

                    b.Property<string>("ReportContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Содержание отчёта по приёму пациента");

                    b.Property<int>("ReportTemplateId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор шаблона отчёта");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentSlotId");

                    b.ToTable("AppointmentResults", t =>
                        {
                            t.HasComment("Результаты приёмов пациентов");
                        });
                });

            modelBuilder.Entity("PolyclinicService.Domain.Models.Entities.AppointmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор слота приёма в графике");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата приёма");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор врача");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasComment("Продолжительность приёма");

                    b.Property<int>("PolyclinicId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор поликлинники");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasComment("Статус приёма в графике");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор пользователя (пациента)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PolyclinicId");

                    b.ToTable("AppointmentSlots", t =>
                        {
                            t.HasComment("Слоты приёма к врачу в графике поликлиники");
                        });
                });

            modelBuilder.Entity("PolyclinicService.Domain.Models.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор врача");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte?>("AcademyDegree")
                        .HasColumnType("smallint")
                        .HasComment("Научная степень врача");

                    b.Property<bool>("IsConfirmedEducation")
                        .HasColumnType("boolean")
                        .HasComment("Признак, что у врача подтвержден документ об образовании");

                    b.Property<bool>("IsConfirmedQualification")
                        .HasColumnType("boolean")
                        .HasComment("Признак, что у врача подтвержден документ о квалификации");

                    b.Property<byte>("QualificationType")
                        .HasColumnType("smallint")
                        .HasComment("Квалификация врача");

                    b.Property<byte>("Seniority")
                        .HasColumnType("smallint")
                        .HasComment("Стаж врача");

                    b.Property<short>("SpecializationType")
                        .HasColumnType("smallint")
                        .HasComment("Специализация врача");

                    b.HasKey("Id");

                    b.ToTable("Doctors", t =>
                        {
                            t.HasComment("Врачи поликлиник");
                        });
                });

            modelBuilder.Entity("PolyclinicService.Domain.Models.Entities.Polyclinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор поликлиники");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Адрес");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Адрес электронной почты");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Наименование поликлиники");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasComment("Номер телефона");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Ссылка на сайт");

                    b.HasKey("Id");

                    b.ToTable("Polyclinics", t =>
                        {
                            t.HasComment("Поликлиники");
                        });
                });

            modelBuilder.Entity("PolyclinicDoctors", b =>
                {
                    b.HasOne("PolyclinicService.Domain.Models.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolyclinicService.Domain.Models.Entities.Polyclinic", null)
                        .WithMany()
                        .HasForeignKey("PolyclinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolyclinicService.Domain.Models.Entities.AppointmentResult", b =>
                {
                    b.HasOne("PolyclinicService.Domain.Models.Entities.AppointmentSlot", "AppointmentSlot")
                        .WithMany()
                        .HasForeignKey("AppointmentSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentSlot");
                });

            modelBuilder.Entity("PolyclinicService.Domain.Models.Entities.AppointmentSlot", b =>
                {
                    b.HasOne("PolyclinicService.Domain.Models.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolyclinicService.Domain.Models.Entities.Polyclinic", "Polyclinic")
                        .WithMany()
                        .HasForeignKey("PolyclinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Polyclinic");
                });
#pragma warning restore 612, 618
        }
    }
}
