// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportService.DAL.Contexts;

#nullable disable

namespace ReportService.DAL.Migrations
{
    [DbContext(typeof(ReportServiceDbContext))]
    [Migration("20251029054506_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReportService.Domain.Models.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор отчёта");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasComment("Содержимое отчёта");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Имя файла");

                    b.Property<byte>("ReportFormat")
                        .HasColumnType("smallint")
                        .HasComment("Формат отчёта");

                    b.HasKey("Id");

                    b.ToTable("Reports", t =>
                        {
                            t.HasComment("Отчёты");
                        });
                });

            modelBuilder.Entity("ReportService.Domain.Models.Entities.ReportTemplateMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор шаблона");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Имя шаблона");

                    b.Property<string>("ReportTemplateTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Наименование типа источника данных для шаблона отчёта в приложении");

                    b.HasKey("Id");

                    b.ToTable("ReportTemplatesMetadata", t =>
                        {
                            t.HasComment("Метаданные по шаблонам отчётов");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
